# name: CI-CD

# on: push

# jobs:

#   build-js:
#     name: Build Js/Css
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v1
#     - name: NPM Build
#       run: |
#         npm install --prefer-offline --no-audit
#         npm run prod
#         cat public/mix-manifest.json
#     - run: Upload build files
#       uses: actions/upload-artifact@v1
#       with:
#         name: assets
#         path: public

#   test-php:
#     name: Test/ Lint PHP
#     runs-on: ubuntu-latest
#     needs: build-js
#     steps:
#       - uses: actions/checkout@v1
#       - name: Setup PHP
#         uses: shivammathur/setup-php@v1
#         with:
#           php-version: 7.4
#           extensions: mbstring, bcmath, pdo, pdo_mysql
#       - name: Composer install
#         run: composer install
#       - name: Run Test
#         run: ./vendor/bin/phpunit

#   deploy:
#     name: Deploy to Production
#     runs-on: ubuntu-latest
#     needs: [build-js, test-php]
#     steps:
#     - uses: actions/checkout@v1

# HOLD FOR NOW