name: Run Lint and PhpInsights

on:
  push:
    branches:
        - develop
        - master

jobs:
  Build-Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Copy environment file
        run: cp .env.example .env

      - name: Copy DockerCompose file
        run: cp docker-compose-example.yml docker-compose.yml

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Build frontend
        run: |
          node -v
          npm -v
          npm install --prefer-offline --no-audit
          ls -a
          npm run build

      - name: Bootup services
        run: |
          docker-compose up -d --build

      - name: Execute tests
        run: docker-compose run --rm composer run test:all